add question section
RecyThing/RecyThing-Web pull request #7
Opened 2023-11-10 05:00 UTC by indrakurr

![screencapture-localhost-5173-2023-11-10-11_53_11](https://github.com/RecyThing/RecyThing-Web/assets/122657032/5566d233-8409-406a-8082-0bbe13f6da58)
![Screenshot 2023-11-10 115500](https://github.com/RecyThing/RecyThing-Web/assets/122657032/26ab0017-e06d-4890-8954-78dc5bc544ad)

2023-11-10 05:16 UTC, TaksaWibawa requested changes

2023-11-10 05:16 UTC, TaksaWibawa commented on src/components/question/question.jsx
> +                    <AccordionIcon />
iconnya diganti sama yang di desain ndra, kalo gasalah ada di library react-iconly yang udah kita install

2023-11-10 05:18 UTC, TaksaWibawa commented on src/components/question/question.jsx
> +                  laboris nisi ut aliquip ex ea commodo consequat.
terus buat konten accordionnya, coba ditanya ke ui/ux, karena kita di tahap slicing ui dan landing page gabakal kita sentuh lagi nanti, jadi dilengkapin dulu semua kontennya

2023-11-10 05:19 UTC, indrakurr commented on src/components/question/question.jsx
> +                    <AccordionIcon />
oke sa

2023-11-10 05:19 UTC, indrakurr commented on src/components/question/question.jsx
> +                  laboris nisi ut aliquip ex ea commodo consequat.
shap

2023-11-10 07:39 UTC, indrakurr commented on src/components/question/question.jsx
> +                  laboris nisi ut aliquip ex ea commodo consequat.
kata yueyuex nya nanti sore baru diisi sa

2023-11-10 07:41 UTC, TaksaWibawa commented on src/components/question/question.jsx
> +                  laboris nisi ut aliquip ex ea commodo consequat.
okehh ndra nunggu itu dulu kalo gitu

2023-11-11 05:53 UTC, indrakurr commented
![screencapture-localhost-5173-2023-11-11-12_51_22](https://github.com/RecyThing/RecyThing-Web/assets/122657032/89fec583-1b35-41a3-b46a-28c0a6fc5cef)
![Screenshot 2023-11-11 125255](https://github.com/RecyThing/RecyThing-Web/assets/122657032/f1821dd2-6118-461a-a99f-fbe9e6f7bfdb)

2023-11-11 16:41 UTC, TaksaWibawa approved these changes
okee mantap!

2023-11-11 16:41 UTC, merged