feat(Halaman-Landing): add animation (#001)
RecyThing/RecyThing-Web pull request #85
Opened 2023-11-29 15:35 UTC by badebess

2023-11-29 18:56 UTC, TaksaWibawa requested changes
ini do, kalo udah diluar dari screen, ada animasi outnya, pake animasi sama tapi direverse aja kali, jadi pas ke section itu lagi bakal muncul lagi animasinya

2023-11-29 23:32 UTC, badebess commented
> ini do, kalo udah diluar dari screen, ada animasi outnya, pake animasi sama tapi direverse aja kali, jadi pas ke section itu lagi bakal muncul lagi animasinya

Oh berarti dia bukan hanya sekali in aja ya mas? , soalny saya ikutin dri prototype punya, disana cuman 1 kali in aja hbs tu stuck

2023-11-30 07:47 UTC, TaksaWibawa commented
> > ini do, kalo udah diluar dari screen, ada animasi outnya, pake animasi sama tapi direverse aja kali, jadi pas ke section itu lagi bakal muncul lagi animasinya
> 
> Oh berarti dia bukan hanya sekali in aja ya mas? , soalny saya ikutin dri prototype punya, disana cuman 1 kali in aja hbs tu stuck

yes betul do

2023-11-30 16:57 UTC, TaksaWibawa approved these changes

2023-11-30 16:57 UTC, merged